### PR TITLE
Fix minor typos in lesson 02.

### PR DESCRIPTION
**Pull request by ghost**
Nicely written :).
This just fixes some minor typos I found. (Please let me know if I should fix something in my commit).

### CODE REVIEW

**Comment by pniedzielski** [comment]
I'm going to change the commit message slightly (so that first line starts with `[component]` and doesn't have a period at the end, and has a license, even though this probably isn't copyrightable), but otherwise, thanks!

**Comment by pniedzielski** [comment]
Merged.

**Comment by ghost** [comment]
Ah, thanks, sorry, I could've done that, will keep in mind next time.
After doing some reading online, I see that going without the period at the end is the way to go for the commit title. And starting the commits with `[component]` also seems cool, I think I might take that up too.

**Comment by pniedzielski** [comment]
Another common technique for doing that is prefixing with `component:`, which has the benefit of using one fewer character :smiley:

A few other common things to do are prefixing commit summaries with `WIP` or `FIXUP` (and a few others I'm forgetting at the moment).  Obviously, we don't want these to be in the final commit history on a public branch, so they give a indicator that they should be rebased away before merging (or creating a pull request).

I'm writing a git guide that will try to motivate and formalize some of these conventions.

**Comment by ghost** [comment]
Ah maybe i'll try `component:`. Sometimes staying under 50 characters can get really difficult :P 

Mm right right.
I remember picking up `[WIP]` from @lidavidm for when working on an active pull request.
I would definitely be interested in your git guide ^_^

**Pull request closed without merging**
